server:
  port: 8083

spring:
  application:
    name: email-service
  profiles:
    active:
      default

  mail:
    host: smtp.qq.com #SMTP服务器地址
    username: jon_1999@foxmail.com #登陆账号
    password: yhfkflsphbwpbbij #登陆密码（或授权码）
    default-encoding: UTF-8
    port: 587

eureka:
  instance:
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html

  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: email.log
