server:
  port: 8099

eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-server
